version: 1.0.{build}
image: Ubuntu

build_scrip:
  - sh: |
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
      \. "$HOME/.nvm/nvm.sh"
      nvm install 22
      node -v
      nvm current
      npm -v
      nvm use 22
install:
  sh: npm install
test_script:
  - sh: npm test
build: off